@startuml
'https://plantuml.com/object-diagram

object Cart
object CartLineItem
object City
object Address
object Account
object Person
object Order
object Inquiry
object Carport
object Shack
object BillOfMaterial
object BillOfMaterialLineItem
object Product
object ProductVariant
object ProductType
object Size


ProductVariant "m"*--"1" Product
ProductVariant "m" *--"1" Size
Product "m"*--"1" ProductType

Account "1" o-- "1" Person
Person "m"*--"1" Address
Address "m"*--"1" City

Inquiry "1" *-- "1" Carport
Inquiry "1" *-- "1" BillOfMaterial
Inquiry "m" o-- "1" Person
BillOfMaterial "1" *-- "m" BillOfMaterialLineItem
BillOfMaterialLineItem "m" o-- "1" ProductVariant
Carport "1" --* "1" Shack

Order "m" *-- "1" Address
Order "1" *-- "1" Inquiry

Cart "1" *-- "m" CartLineItem
CartLineItem "m" *-- "1" ProductVariant


@enduml
