@startuml
'https://plantuml.com/state-diagram

Title Navigationsdiagram for Fog website v2


State index.jsp
State navigationbar
note left of navigationbar
    When a user is not logged in,
    the user can then always access
    the jsps in LoginOrRegister state
end note
note bottom of navigationbar
    When a user is logged on,
    the user can then always access
    the jsps inside of LoggedOn state
    and also the ones inside
    LoggedOnAsEmployeeOrAdmin if
    the user is an employee or admin
end note

[*] --> index.jsp
index.jsp --> navigationbar
index.jsp --> carportFlatRoof.jsp
index.jsp --> carportSlopeRoof.jsp
carportFlatRoof.jsp --> index.jsp
carportSlopeRoof.jsp --> index.jsp
carportFlatRoof.jsp --> carportSlopeRoof.jsp
carportSlopeRoof.jsp --> carportFlatRoof.jsp
navigationbar --> index.jsp


State LoginOrRegister {
    State exit <<exitPoint>>
    State login.jsp
    State register.jsp

    login.jsp --> login.jsp: Log på [fejl]
    login.jsp --> exit: Log på [ok]
    register.jsp --> register.jsp: Registrer [fejl]
    register.jsp --> exit: Registrer [ok]

}


note right of LoggedOn
    This state is reachable
    ONLY if the user has logged in
end note
state LoggedOn {
    State account.jsp
    State logout.jsp
    State myInquires.jsp
    [H] --> index.jsp: Bruger dirigeres til index \n når der logges ind
    logout --> index.jsp: Bruger dirigeres til \n index efter udlogning
}
exit --> LoggedOn[H]


note bottom of LoggedOnAsEmployeeOrAdmin
    This state is reachable
    ONLY if the user has logged in
    AND has the role Admin or Employee
end note
State LoggedOnAsEmployeeOrAdmin {
    State employeeDashboard.jsp
    State materialer.jsp
    note bottom of employeeDashboard.jsp
            Seller views and processes
            inquiries here
    end note
    note bottom of materialer.jsp
                Admin sees and
                edits materials here
    end note
}



@enduml